### ISSUE TITLE
captiveflask no more running 

### ISSUE THREAD

**Issue by ruffelf** [P0cL4bs/wifipumpkin3#103]
after updating kali today , the entire captiveflask dont work , return this when i try to use native captive portal 👍 

[  captiveflask  ] 18:24:32  - Traceback (most recent call last):
  File "/usr/local/bin/captiveflask", line 4, in <module>
    __import__('pkg_resources').run_script('wifipumpkin3==1.0.7', 'captiveflask')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1434, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/captiveflask' not found in metadata at '/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7.dist-info'

and this when i try to use downloaded captive portal :

[*] redirecting HTTP traffic to captive portal
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.0.7', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/__main__.py", line 106, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 44, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 166, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/console.py", line 216, in do_start
    ctr_instance.Start()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/controllers/proxycontroller.py", line 128, in Start
    self.Active.boot()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/servers/proxy/captiveflask.py", line 124, in boot
    self.reactor = ProcessThread({"captiveflask": self.CMD_ARRAY})
AttributeError: 'CaptivePortal' object has no attribute 'CMD_ARRAY'
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.

i updating kali with a standard apt-get update && apt-get upgrade , and run captiveportal 
i reinstall many time wifipumkin3 , with one total uninstall

![Screenshot_2020-11-09_18-33-02](https://user-images.githubusercontent.com/43814103/98575921-b4095b80-22b1-11eb-9e56-3ef5a25602aa.png)

* Wifipumpkin3 version v1.0.7
* Virtual Machine (yes or no and which): no , persistant usb 
* Operating System: kali linux 
* version: 2020.4

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
execute the command to reinstall the wp3:
``` sh
sudo python3.7 setup.py install  
```
