### ISSUE TITLE
Captiveflask

### ISSUE THREAD

**Issue by CraftedCat** [P0cL4bs/wifipumpkin3#110]
Kali 2020.4
1.0.8
after add custom temlate for captiveportal and run python3 setup.py install

Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 11, in <module>
    load_entry_point('wifipumpkin3==1.0.8', 'console_scripts', 'wifipumpkin3')()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/__main__.py", line 161, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 44, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 166, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/console.py", line 216, in do_start
    ctr_instance.Start()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/controllers/proxycontroller.py", line 127, in Start
    self.Active.boot()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/servers/proxy/captiveflask.py", line 121, in boot
    self.reactor = ProcessThread({"captiveflask": self.CMD_ARRAY})
AttributeError: 'CaptivePortal' object has no attribute 'CMD_ARRAY'

**Comment by CraftedCat** [comment]
my bad
