### ISSUE TITLE
Does NOT work on python3.9.1rc1&kali-linux-2020.4 env

### ISSUE THREAD

**Issue by ch-luckylai** [P0cL4bs/wifipumpkin3#115]
## What happened

I cloned wifipumpkin3([commit 3b0b530](https://github.com/P0cL4bs/wifipumpkin3/commit/3b0b5307a1b01ef396d794bb37a605999ff8dce4)) into my kali linux(2020.4) and updated my python to 3.9.1rc1.

And I found it doesn't work.

## Steps

1. install requirements with requirements.txt
`pip install -r requirements.txt`

2. install wifipumpkin3
`python3 setup.py install`

3.type wifipumpkin3 in bash
`wifipumpkin3`

then it gave me a traceback:

`
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.0.8', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/bin/wifipumpkin3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/__init__.py", line 1, in <module>
    from wifipumpkin3.core.common.console import PumpkinShell
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/console.py", line 1, in <module>
    from wifipumpkin3.core.common.terminal import ConsoleUI
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/terminal.py", line 7, in <module>
    from wifipumpkin3.core.common.platforms import Linux
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/platforms.py", line 7, in <module>
    from scapy.all import *
  File "/usr/lib/python3/dist-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'
`

## Version : 

Well , I COULD NOT use "wifipumpkin3 --version" AT ALL!

[commit 3b0b530](https://github.com/P0cL4bs/wifipumpkin3/commit/3b0b5307a1b01ef396d794bb37a605999ff8dce4)

## My opinion :

It may be a bug caused by scapy module(maybe It hasn't been upgraded to python3.9.1rc1).

Thank you !

PS: My English is poor :(

**Comment by ch-luckylai** [comment]
This is the Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.0.8', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/bin/wifipumpkin3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/__init__.py", line 1, in <module>
    from wifipumpkin3.core.common.console import PumpkinShell
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/console.py", line 1, in <module>
    from wifipumpkin3.core.common.terminal import ConsoleUI
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/terminal.py", line 7, in <module>
    from wifipumpkin3.core.common.platforms import Linux
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/platforms.py", line 7, in <module>
    from scapy.all import *
  File "/usr/lib/python3/dist-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'
```

Oh sorry I used inline-code :(

**Comment by shyhn** [comment]
Same issue here and same configuration... Tried to download libs and look over internet but after few hours still not working :/

**Comment by shyhn** [comment]
I found the solution : 
You need to install manually scapy (and urwid in my case) :
git clone https://github.com/secdev/scapy
cd scapy
./run_scapy

Hope it will solve your problem mate

**Comment by wowanbelousov** [comment]
**A similar problem**

└─#  wifiphisher
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/bin/wifiphisher", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 25, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/lib/python3/dist-packages/wifiphisher/common/extensions.py", line 12, in <module>
    import scapy.arch.linux as linux
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

**Comment by s0i37** [comment]
python3.9 devels fuck of !!!

```
cd /usr/lib/x86_64-linux-gnu/
ln -s -f libc.a liblibc.a
```

**Comment by ch-luckylai** [comment]
> python3.9 devels fuck of !!!
> 
> ```
> cd /usr/lib/x86_64-linux-gnu/
> ln -s -f libc.a liblibc.a
> ```

It works !

Thanks ! :+1:

**Comment by codingbeast** [comment]
> python3.9 devels fuck of !!!
> 
> ```
> cd /usr/lib/x86_64-linux-gnu/
> ln -s -f libc.a liblibc.a
> ```

Working . Thankyou

**Comment by mh4x0f** [comment]
> I found the solution :
> You need to install manually scapy (and urwid in my case) :
> git clone https://github.com/secdev/scapy
> cd scapy
> sudo python3 setup.py install

the scapy not support python 3.9 from pip look on [pyPi](https://pypi.org/project/scapy/), the scapy from git has been added support py 3.9 look [gitaction](https://github.com/secdev/scapy/actions/runs/297317494/workflow) because this install the scapy from git solve the problem

**Comment by mh4x0f** [comment]
> python3.9 devels fuck of !!!
> 
> ```
> cd /usr/lib/x86_64-linux-gnu/
> ln -s -f libc.a liblibc.a
> ```

thank's for help the users brow, this is better option to solve the problem.

**Comment by n07f0und** [comment]
> python3.9 devels fuck of !!!
> 
> ```
> cd /usr/lib/x86_64-linux-gnu/
> ln -s -f libc.a liblibc.a
> ```

very nice its working now

**Comment by root-ali** [comment]
> python3.9 devels fuck of !!!
> 
> ```
> cd /usr/lib/x86_64-linux-gnu/
> ln -s -f libc.a liblibc.a
> ```

very nice work for me 

in manjaro linux

```
sudo ln -s  /usr/lib/libc.a /usr/lib/liblibc.a
```

**Comment by gustavovg** [comment]
Hello guys, can someone help me with this please, when I apply the code

sudo python3 setup.py install

it displays the following error:

Extracting wifipumpkin3-1.0.8-py3.9.egg to /usr/local/lib/python3.9/site-packages
wifipumpkin3 1.0.8 is already the active version in easy-install.pth
Installing captiveflask script to /usr/local/bin
Installing sslstrip3 script to /usr/local/bin
Installing wifipumpkin3 script to /usr/local/bin

Installed /usr/local/lib/python3.9/site-packages/wifipumpkin3-1.0.8-py3.9.egg
Processing dependencies for wifipumpkin3==1.0.8
Searching for Werkzeug==1.0.1
Reading https://pypi.org/simple/Werkzeug/
Download error on https://pypi.org/simple/Werkzeug/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'Werkzeug' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for Werkzeug==1.0.1
error: Could not find suitable distribution for Requirement.parse('Werkzeug==1.0.1')
