### ISSUE TITLE
Having nothing but problems on install. Would love to use wifipumkin3. Any help?

### ISSUE THREAD

**Issue by thisisdfresh** [P0cL4bs/wifipumpkin3#121]
I am using the latest version of Kali Linux on a Raspberry Pi 4. I'm connected to the internet via Ethernet. I made sure to update and upgrade first as I normally do. First I followed the instructions given on Null-byte only to find that it needs updated because there were issues with the install. I removed the files and found this site and began a new installation. Everything went fine and I even got this: "Finished processing dependencies for wifipumpkin3==1.0.8"  After... kali@kali:/wifipumpkin3$ sudo wifipumpkin3.....   I got this very long message:
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.0.8', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/bin/wifipumpkin3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/__init__.py", line 1, in <module>
    from wifipumpkin3.core.common.console import PumpkinShell
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/console.py", line 2, in <module>
    from wifipumpkin3.core.controllers.defaultcontroller import *
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/controllers/defaultcontroller.py", line 11, in <module>
    from wifipumpkin3.core.controllers.uicontroller import *
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/controllers/uicontroller.py", line 4, in <module>
    from wifipumpkin3.core.ui import *
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/ui/uimode.py", line 1, in <module>
    import urwid
  File "/usr/local/lib/python3.9/dist-packages/urwid-2.1.1-py3.9-linux-aarch64.egg/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/usr/local/lib/python3.9/dist-packages/urwid-2.1.1-py3.9-linux-aarch64.egg/urwid/widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/usr/local/lib/python3.9/dist-packages/urwid-2.1.1-py3.9-linux-aarch64.egg/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/usr/local/lib/python3.9/dist-packages/urwid-2.1.1-py3.9-linux-aarch64.egg/urwid/util.py", line 58, in detect_encoding
    locale.setlocale(locale.LC_ALL, initial)
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by cjb900** [comment]
you will want to look at this closed issue here https://github.com/P0cL4bs/wifipumpkin3/issues/115
