### ISSUE TITLE
Problems and solutions in running projects with dockerfile

### ISSUE THREAD

**Issue by jinhay** [P0cL4bs/wifipumpkin3#129]
**Description of the bug or feature request**

When I use docker to run the project, I hope to solve the problem from the project

Error starting container after using dockerfile to build image

Error message: locale.Error : unsupported locale setting

My solution is to add the

ENV LC_ ALL=C

When using dockerfile to build the image, I rely on reporting an error. I have finished building the image, and the error has been lost. I'm very sorry

My solution is in the requirements.txt add to

cryptography==3.2.1

**To Reproduce**
1. docker build -t "wifipumpkin3" .

Screenshots
**Desktop (please complete the following information):wifipumpkin3 v1.0.8 branch: dev

Virtual Machine yes docker
Operating System: ubuntu
version: Ubuntu 7.5.0-3ubuntu1~18.04

My English is not good, please forgive me if you have any offence。

It's a great project. I like it very much

**Comment by mh4x0f** [comment]
> Error message: locale.Error : unsupported locale setting

this error is not caused be tool, probably it a error come from urwid version and can be solved with simple past on google. 


> When using dockerfile to build the image, I rely on reporting an error. I have finished building the image, and the error has been lost. I'm very sorry

I 'll checkout

**Comment by mh4x0f** [comment]
I recommend to use the docker compose method.

**Comment by oza6ut0ne** [comment]
> probably it a error come from urwid version

Hi, I have the same issue here.
```python3
Traceback (most recent call last):                                                                                                                                                                                  
  File "/usr/local/bin/wifipumpkin3", line 11, in <module>                                                                                                                                                          
    load_entry_point('wifipumpkin3==1.0.8', 'console_scripts', 'wifipumpkin3')()                                                                                                                                    
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point                                                                                                                    
    return get_distribution(dist).load_entry_point(group, name)                                                                                                                                                     
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point                                                                                                                   
    return ep.load()                                                                                                                                                                                                
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load                                                                                                                               
    return self.resolve()                                                                                                                                                                                           
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve                                                                                                                            
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                                                                                           
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/__init__.py", line 1, in <module>                                                                                          
    from wifipumpkin3.core.common.console import PumpkinShell                                                                                                                                                       
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/core/common/console.py", line 2, in <module>                                                                               
    from wifipumpkin3.core.controllers.defaultcontroller import *                                                                                                                                                   
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/core/controllers/defaultcontroller.py", line 11, in <module>                                                               
    from wifipumpkin3.core.controllers.uicontroller import *                                                                                                                                                        
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/core/controllers/uicontroller.py", line 4, in <module>                                                                     
    from wifipumpkin3.core.ui import *
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/core/ui/uimode.py", line 1, in <module>
    import urwid
  File "/usr/local/lib/python3.7/dist-packages/urwid/__init__.py", line 26, in <module>
    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
  File "/usr/local/lib/python3.7/dist-packages/urwid/widget.py", line 27, in <module>
    from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
  File "/usr/local/lib/python3.7/dist-packages/urwid/util.py", line 61, in <module>
    detected_encoding = detect_encoding()
  File "/usr/local/lib/python3.7/dist-packages/urwid/util.py", line 58, in detect_encoding
    locale.setlocale(locale.LC_ALL, initial)
  File "/usr/lib/python3.7/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
This is an error [from urwid](https://github.com/urwid/urwid/issues/377), and [fixed in urwid 2.1.2](https://github.com/urwid/urwid/pull/415).
Updating urwid fixed the problem for me.

**Comment by oza6ut0ne** [comment]
@mh4x0f
Sent a PR for this (#134). Please check it.

**Comment by mh4x0f** [comment]
@oza6ut0ne  thanks for support
