### ISSUE TITLE
ModuleNotFoundError: No module named 'wifipumpkin3.modules.wifi.exceptions

### ISSUE THREAD

**Issue by VioletL-in** [P0cL4bs/wifipumpkin3#143]
The error occurred when I run the command `sudo wifipumpkin3`. I have installed the wifipumpkin3 with `Finished processing dependencies for wifipumpkin3==1.0.8`. How to fix the error?

The detail of the error is:
```
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.0.8', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/__main__.py", line 160, in main
    prompt = PumpkinShell(parse_args)
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/core/common/console.py", line 62, in __init__
    super(PumpkinShell, self).__init__(parse_args=self.parse_args)
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/core/common/terminal.py", line 36, in __init__
    self.initialize_core()
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/core/common/console.py", line 71, in initialize_core
    self.all_modules = module_list
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/core/common/console.py", line 131, in all_modules
    for name, module in module_list().items():
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/modules/__init__.py", line 45, in module_list
    return import_submodules(__name__)
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/modules/__init__.py", line 23, in import_submodules
    results[short_name] = importlib.import_module(full_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wifipumpkin3.modules.wifi.exceptions'
```

Other information may be helpful:
* Wifipumpkin3 version: wifipumpkin3 v1.0.8 branch: dev
* Virtual Machine: VMware® Workstation 15 Pro, 15.5.5 build-16285975
* Operating System: Ubuntu-18.04.1

**Comment by ifrahazmi** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.1.7', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.7-py3.10.egg/wifipumpkin3/__main__.py", line 256, in main
    prompt = PumpkinShell(parse_args)
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.7-py3.10.egg/wifipumpkin3/core/common/console.py", line 62, in __init__
    super(PumpkinShell, self).__init__(parse_args=self.parse_args)
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.7-py3.10.egg/wifipumpkin3/core/common/terminal.py", line 129, in __init__
    self.initialize_core()
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.7-py3.10.egg/wifipumpkin3/core/common/console.py", line 74, in initialize_core
    self.all_modules = module_list
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.7-py3.10.egg/wifipumpkin3/core/common/console.py", line 150, in all_modules
    for name, module in module_list().items():
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.7-py3.10.egg/wifipumpkin3/modules/__init__.py", line 45, in module_list
    return import_submodules(__name__)
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.7-py3.10.egg/wifipumpkin3/modules/__init__.py", line 23, in import_submodules
    results[short_name] = importlib.import_module(full_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wifipumpkin3.modules.wifi.exceptions'
