### ISSUE TITLE
error: Couldn't find a setup script in /tmp/easy_install-rad8_t5b/PyQt5-5.14.0.tar.gz

### ISSUE THREAD

**Issue by koko5888** [P0cL4bs/wifipumpkin3#15]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

 error: Couldn't find a setup script in /tmp/easy_install-57gbmkqb/PyQt5-5.14.0.tar.gz
when doing the command sudo make install at the end of the installation 

Installed /usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.0-py3.7.egg
Processing dependencies for wifipumpkin3==1.0.0
Searching for PyQt5==5.14
Reading https://pypi.org/simple/PyQt5/
Downloading https://files.pythonhosted.org/packages/7c/5b/e760ec4f868cb77cee45b4554bf15d3fe6972176e89c4e3faac941213694/PyQt5-5.14.0.tar.gz#sha256=0145a6b7de15756366decb736c349a0cb510d706c83fda5b8cd9e0557bc1da72
Best match: PyQt5 5.14.0
Processing PyQt5-5.14.0.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-rad8_t5b/PyQt5-5.14.0.tar.gz
make: *** [makefile:11: install] Error 1

install wifipumpkin3 CLI 

**Expected behavior**
gives me an error when running wifipumpkin3

**Screenshots**

**Desktop (raspberry pi 3 b+):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).
* Virtual Machine (no): 
* Operating System:kali lunix
* version: 2020.1a arm

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
the **PyQt5  5.14.0** is broken because can't not install on **resp pi 3** . you can to install a version of PyQt5 that working fine on resp. follow the steps:
``` sh
sudo apt-get update -y
sudo apt-get install -y python3-pyqt5
python3 --version
```
now, with PyQt5 installed on system only to check if everything ok:
``` sh
python3 -c "from PyQt5.QtCore import QSettings; print('done')"
```
 if you got the message `done`, nice. the next step is **remove somes lines** from file **requirements.txt** on root the wifipumpkin3 project. Open the file and delete this lines:
``` 
PyQt5==5.14
PyQt5-sip==12.7.2
```
great, now  you can install the tool:
``` sh
python3 setup.py install 
```
> Finished processing dependencies for wifipumpkin3==1.0.0
done, if you got here, execute the tool with:
```
sudo wifipumpkin3
```
send me the feedback! nice report.

**Comment by koko5888** [comment]
I did all of that but then this happened



$$$$$$$$$$$$$$$$$$$$$$$$$$$$$PR$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$$"    @$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$"      '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$                 """"""#*R$$$$$$$$$$$$$
$$$$$$$$$$$$$P"..::!~ .....    .<!!!!!!!:  ~!!!:.. "*$$$$$$$$$
$$$$$$$$$$".<!!!!~  <!!!!!!!~ !!!!!!!!!!!!!  !!!!!!!: "$$$$$$$
$$$$$$$P <!!!!!~ .!!!!!!!!!! !!!!!!!!!!!!!!!. `!!!!!!!: "$$$$$
$$$$$P :!!!!!~ .!!!!~!!!!!! .!!!!!!!!!~!!!!!!: '!!!!!!!! '$$$$
$$$$# !!!!!f  !!!`   `!!!!! :!!!!!!!!!    `!!!! `!!!!!!!! '$$$
$$$F !!!!!!  !!~      '!!!f  4!!!!!!!!       !!> 4!!!!!!!> 9$$
$$P <!!!!!  !!>        '!!~   '!!!!!!........<!!  !!!!!!!! <$$
$$> !!!!!! ~!!!!!!!!!!!!!~      `!!!!!!!!!!!!!!!> `!!!!!!!  $$
$$ '!!!!!! '!!!!!!!!!!!!!!> !!!!!!!!!!!!!!(``~!!!  !!!!!!f 4$$
$$r!!!!!!! `!!~   :<!!!!!!! `!!!!!!!!!!!!!~    `! '!!!!!!> .$$
$$L !!!!!!. !!:h   `!!!!!!! `!!!!!!!!!~     <!!!!  !!!!!!  @$$
$$$ `!!!!!! ~!!!!       `~~ '~~~~~`        !!!!!f .!!!!!  <$$$
$$$N ~!!!!!! !!!!!h.           ..::     .!!!!!!!  :!!!!` .$$$$
$$$$$. ~!!!!> !!!!!!!!:       `!!!!!h!!!!!!!!!!~  !!!!  d$$$$$
$$$$$$N. `!!!. !!!!!!!!!!!!! ~!!!!!!!!!!!!!!!!~  !!~ .e$$$$$$$
$$$$$$$$$bu  `  '!!!!!!!!!!~  !!!!!!!!!!!!!~` .uuue$$$$$$$$$$$
$$$$$$$$$$$$$$$$e.  ````   wifi     ```   .e$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
                                            codename: nidavellir
Made by: @mh4x0f - P0cL4bs Team | 1.0.0 dev
[*] Session id: 4448f6c0-827a-11ea-a103-b827eb5011c3
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 4, in <module>
    __import__('pkg_resources').run_script('wifipumpkin3==1.0.0', 'wifipumpkin3')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/EGG-INFO/scripts/wifipumpkin3", line 102, in <module>
    prompt = PumpkinShell(parse_args)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__init__.py", line 62, in __init__
    super(PumpkinShell, self).__init__(parse_args=self.parse_args)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 35, in __init__
    self.initialize_core()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__init__.py", line 73, in initialize_core
    self.coreui = DefaultController(self)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/controllers/defaultcontroller.py", line 45, in __init__
    __defaultui = [ui(parent, self.FSettings) for ui in TabsWidget.__subclasses__()]
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/controllers/defaultcontroller.py", line 45, in <listcomp>
    __defaultui = [ui(parent, self.FSettings) for ui in TabsWidget.__subclasses__()]
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/widgets/default/plugins.py", line 30, in __init__
    self.__plugins = [plug(parent) for plug in PluginsUI.__subclasses__()]
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/widgets/default/plugins.py", line 30, in <listcomp>
    self.__plugins = [plug(parent) for plug in PluginsUI.__subclasses__()]
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/controllers/proxycontroller.py", line 46, in __init__
    __proxlist = [
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/controllers/proxycontroller.py", line 47, in <listcomp>
    prox(parent=self.parent) for prox in proxymode.ProxyMode.__subclasses__()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/servers/proxy/no_proxy.py", line 31, in __init__
    super(NoProxy, self).__init__(parent)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/servers/proxy/proxymode.py", line 80, in __init__
    self.loggermanager = LoggerManager.getInstance()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/widgets/default/logger_manager.py", line 173, in getInstance
    return cls.instances[0]
IndexError: list index out of range

**Comment by mh4x0f** [comment]
#14  this problem has been solved update the project:
```
git pull 
```

**Comment by koko5888** [comment]
git pull https://github.com/P0cL4bs/wifipumpkin3.git
got
fatal: not a git repository (or any of the parent directories): .git

**Comment by koko5888** [comment]
thanks that worked
