### ISSUE TITLE
I get an error [Errno 13] Permission Denied

### ISSUE THREAD

**Issue by papapapapython** [P0cL4bs/wifipumpkin3#157]
I run the script as admin and I still get the error.
If anyone knows why its happening please tell
Thank you
OS:Kali Linux

**Comment by Tarrylim** [comment]
could you show me the code?

**Comment by papapapapython** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.0.8', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/bin/wifipumpkin3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/__init__.py", line 1
, in <module>
    from wifipumpkin3.core.common.console import PumpkinShell
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/console.
py", line 1, in <module>
    from wifipumpkin3.core.common.terminal import ConsoleUI
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/terminal
.py", line 7, in <module>
    from wifipumpkin3.core.common.platforms import Linux
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/common/platform
s.py", line 7, in <module>
    from scapy.all import *
  File "/usr/local/lib/python3.9/dist-packages/scapy-2.4.5-py3.9.egg/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/local/lib/python3.9/dist-packages/scapy-2.4.5-py3.9.egg/scapy/arch/__init__.py", line 135, in <m
odule>
    _set_conf_sockets()  # Apply config
  File "/usr/local/lib/python3.9/dist-packages/scapy-2.4.5-py3.9.egg/scapy/config.py", line 618, in _set_conf
_sockets
    conf.ifaces.reload()
  File "/usr/local/lib/python3.9/dist-packages/scapy-2.4.5-py3.9.egg/scapy/interfaces.py", line 238, in reloa
d
    self._reload_provs()
  File "/usr/local/lib/python3.9/dist-packages/scapy-2.4.5-py3.9.egg/scapy/interfaces.py", line 234, in _relo
ad_provs
    self._load(prov.reload(), prov)
  File "/usr/local/lib/python3.9/dist-packages/scapy-2.4.5-py3.9.egg/scapy/interfaces.py", line 53, in reload
    return self.load()
  File "/usr/local/lib/python3.9/dist-packages/scapy-2.4.5-py3.9.egg/scapy/arch/linux.py", line 420, in load
    get_if_raw_hwaddr(i, siocgifhwaddr=SIOCGIFHWADDR)[1]
  File "/usr/local/lib/python3.9/dist-packages/scapy-2.4.5-py3.9.egg/scapy/arch/common.py", line 87, in get_i
f_raw_hwaddr
    get_if(iff, siocgifhwaddr)
  File "/usr/local/lib/python3.9/dist-packages/scapy-2.4.5-py3.9.egg/scapy/arch/common.py", line 65, in get_i
f
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
PermissionError: [Errno 13] Permission denied

**Comment by Tarrylim** [comment]
https://careerkarma.com/blog/python-permissionerror-errno-13-permission-denied/

I hope this help you, this is same with your problem and it will give you solution
