### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtCore'

### ISSUE THREAD

**Issue by jepunband** [P0cL4bs/wifipumpkin3#182]
**Description of the bug or feature request**

ModuleNotFoundError: No module named 'PyQt5.QtCore'

setup completed:
Using /usr/local/lib/python3.7/site-packages
Finished processing dependencies for wifipumpkin3==1.1.2

i have pyqt5:
sudo apt install python3-pyqt5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pyqt5 is already the newest version (5.15.6+dfsg-1+b1).
The following packages were automatically installed and are no longer required:
  libpython2-dev libpython2.7 libpython2.7-dev python2-dev python2.7-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

also tried this:
python -m pip install pyqt5 -U
Requirement already satisfied: pyqt5 in /usr/lib/python3/dist-packages (5.15.6)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/lib/python3/dist-packages (from pyqt5) (12.9.1)

**To Reproduce**
1. sudo wifipumpkin3

**Expected behavior**
wifipumkin3 should launch

**Screenshots**
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.1.2', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/bin/wifipumpkin3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/wifipumpkin3-1.1.2-py3.7.egg/wifipumpkin3/__init__.py", line 1, in <module>
    from wifipumpkin3.core.common.console import PumpkinShell
  File "/usr/local/lib/python3.7/site-packages/wifipumpkin3-1.1.2-py3.7.egg/wifipumpkin3/core/common/console.py", line 1, in <module>
    from wifipumpkin3.core.common.terminal import ConsoleUI
  File "/usr/local/lib/python3.7/site-packages/wifipumpkin3-1.1.2-py3.7.egg/wifipumpkin3/core/common/terminal.py", line 4, in <module>
    from wifipumpkin3.core.utility.collection import SettingsINI
  File "/usr/local/lib/python3.7/site-packages/wifipumpkin3-1.1.2-py3.7.egg/wifipumpkin3/core/utility/collection.py", line 2, in <module>
    from PyQt5.QtCore import QSettings
ModuleNotFoundError: No module named 'PyQt5.QtCore'

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).
* Virtual Machine (yes or no and which): no
* Operating System: Kali
* version: 
ID=kali
VERSION="2022.1"
VERSION_ID="2022.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
You need to install on python with pythonqt5 installed. try this: run this command bellow:

```
python3 -c "from PyQt5.QtCore import QSettings; print('done')"
```

if you got the message `done` now only install on python3:

```
sudo python3 setup.py install
```
