### ISSUE TITLE
Error when scanning wifi via wifi.wifideauth: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by RiotGamesU** [P0cL4bs/wifipumpkin3#186]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

Error when scanning wifi via wifi.wifideauth: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
wifipumpkin3 will print some wifi normally, then report the above error
I guess it's a problem with the Chinese ssid

**To Reproduce**
1. 
```bash
┌──(root㉿kali)-[~]
└─# wifipumpkin3                                                  

  _      ___ _____     ___                  __    _      ____
 | | /| / (_) __(_)___/ _ \__ ____ _  ___  / /__ (_)__  |_  /
 | |/ |/ / / _// /___/ ___/ // /  ' \/ _ \/  '_// / _ \_/_ < 
 |__/|__/_/_/ /_/   /_/   \_,_/_/_/_/ .__/_/\_\/_/_//_/____/ 
                                   /_/                       
                                            codename: Yorixiriamori
by: @mh4x0f - P0cL4bs Team | version: 1.1.2 dev
[*] Session id: 898f955a-eed3-11ec-a845-000c293e1d5c 
Starting prompt...
wp3 > use wifi.wifideauth
wp3 : wifideauth > set interface wlan0
wp3 : wifideauth > scan
```
2.
```bash
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.1.2', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.2-py3.10.egg/wifipumpkin3/__main__.py", line 162, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.2-py3.10.egg/wifipumpkin3/core/common/terminal.py", line 117, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.2-py3.10.egg/wifipumpkin3/core/common/terminal.py", line 85, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.2-py3.10.egg/wifipumpkin3/core/common/console.py", line 195, in do_use
    return module.cmdloop()
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.2-py3.10.egg/wifipumpkin3/core/common/terminal.py", line 383, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.2-py3.10.egg/wifipumpkin3/modules/wifi/wifideauth.py", line 193, in do_scan
    sniff(
  File "/usr/local/lib/python3.10/dist-packages/scapy/sendrecv.py", line 1263, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scapy/sendrecv.py", line 1210, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python3.10/dist-packages/scapy/sessions.py", line 108, in on_packet_received
    result = self.prn(pkt)
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.2-py3.10.egg/wifipumpkin3/modules/wifi/wifideauth.py", line 462, in sniffAp
    self.showDataOutputScanNetworks()
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.2-py3.10.egg/wifipumpkin3/modules/wifi/wifideauth.py", line 430, in showDataOutputScanNetworks
    display_tabulate(self.table_headers_wifi, self.table_output)
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.2-py3.10.egg/wifipumpkin3/core/utility/printer.py", line 100, in display_tabulate
    print(tabulate(content, header, tablefmt=tablefmt, **kwargs))
  File "/usr/lib/python3/dist-packages/tabulate.py", line 1591, in tabulate
    cols = [
  File "/usr/lib/python3/dist-packages/tabulate.py", line 1592, in <listcomp>
    [_format(v, ct, fl_fmt, miss_v, has_invisible) for v in c]
  File "/usr/lib/python3/dist-packages/tabulate.py", line 1592, in <listcomp>
    [_format(v, ct, fl_fmt, miss_v, has_invisible) for v in c]
  File "/usr/lib/python3/dist-packages/tabulate.py", line 984, in _format
    return _text_type(val, "ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

**Expected behavior**
Normal printing wifi

**Screenshots**
None

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).wifipumpkin3 v1.1.2 branch: dev
* Virtual Machine (yes or no and which): yes, vmware
* Operating System:
```bash
┌──(root㉿kali)-[~]
└─# cat /etc/*-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.2"
VERSION_ID="2022.2"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```
* version: 
```bash
┌──(root㉿kali)-[~]
└─# cat /proc/version              
Linux version 5.17.0-kali3-amd64 (devel@kali.org) (gcc-11 (Debian 11.3.0-3) 11.3.0, GNU ld (GNU Binutils for Debian) 2.38) #1 SMP PREEMPT Debian 5.17.11-1kali1 (2022-05-30)
```

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
#104
