### ISSUE TITLE
clients crash

### ISSUE THREAD

**Issue by Azrael1980** [P0cL4bs/wifipumpkin3#198]
Kali-2022.2 virtual machine.  latest build. AP starts, but no visible in list of networks

 bssid             | ssid      |   channel | interface   | status      | security   | hostapd_config
-------------------+-----------+-----------+-------------+-------------+------------+------------------
 0000000000 | 000000000 |        11 | wlan0       | not Running | false      | false

wp3 > ignore pydns_server
wp3 > start
[+] enable forwarding in iptables...
[*] sharing internet connection with NAT...
[+] starting hostpad pid: [22433]
wp3 > [+] hostapd is running
[*] starting pydhcp_server
[*] starting pydns_server
[*] starting sniffkin3 port: [80, 8080]
[+] sniffkin3 -> ftp        activated
[+] sniffkin3 -> hexdump    activated
[+] sniffkin3 -> emails     activated
[+] sniffkin3 -> httpCap    activated
[+] sniffkin3 -> kerberos   activated

wp3 > clients
Traceback (most recent call last):
  File "/usr/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.1.3', 'console_scripts', 'wifipumpkin3')())
  File "/usr/lib/python3/dist-packages/wifipumpkin3/__main__.py", line 168, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/common/terminal.py", line 120, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/common/terminal.py", line 88, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/common/console.py", line 315, in do_clients
    self.uiwid_controller.ui_table_mod.start()
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/ui/table.py", line 91, in start
    self.main()
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/ui/table.py", line 78, in main
    self.setup_view()
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/ui/table.py", line 62, in setup_view
    self.header_wid = urwid.AttrWrap(urwid.Text(self.header_text), "title")
NameError: name 'urwid' is not defined
QProcess: Destroyed while process ("/usr/sbin/hostapd") is still running.

**Comment by mh4x0f** [comment]
Hi, this bug has been solved in this commit e82afd1519ec399fee6e75c315420776e1ad6df3, please install the current version on github or install the .deb package on release sections.
