### ISSUE TITLE
wifipumpking3 in Ubuntu 22.04

### ISSUE THREAD

**Issue by eprompc** [P0cL4bs/wifipumpkin3#222]
Hello. 
I have Ubuntu 22.04 with Gnome, and I'm trying to use wp3 in my Lenovo Laptop.

I git clone last compilation 
`git clone https://github.com/P0cL4bs/wifipumpkin3.git
cd wifipumpkin3`

and then
`sudo python3.10 setup.py install`

because Ubuntu have Python3.10 and not Python3.7
Then instalation process succed without errors.

But when run sudo ./wifipumkin3 I get this error:

`╰─ sudo wifipumpkin3                                                                                                                    ─╯
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.1.4', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/bin/wifipumpkin3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.4-py3.10.egg/wifipumpkin3/__init__.py", line 1, in <module>
    from wifipumpkin3.core.common.console import PumpkinShell
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.4-py3.10.egg/wifipumpkin3/core/common/console.py", line 1, in <module>
    from wifipumpkin3.core.common.terminal import ConsoleUI
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.4-py3.10.egg/wifipumpkin3/core/common/terminal.py", line 3, in <module>
    from wifipumpkin3.core.servers.dhcp.dhcp import DHCPServers
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.4-py3.10.egg/wifipumpkin3/core/servers/dhcp/dhcp.py", line 3, in <module>
    from wifipumpkin3.core.config.globalimport import *
  File "/usr/local/lib/python3.10/dist-packages/wifipumpkin3-1.1.4-py3.10.egg/wifipumpkin3/core/config/globalimport/__init__.py", line 5, in <module>
    from PyQt5 import QtCore, Qt
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory

`
I have all the dependencies properly installed, and I don't know what the error is due to. 
If someone can help me.

Thank you very much

**Comment by mh4x0f** [comment]
you need to install the PyQt5 for python3.10
```
sudo apt install python3-pyqt5
```

if not working, your need to  find a solution on google, only need to do is put this error on google:

```
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
```
