### ISSUE TITLE
[bug] wifipumpkin crash and AP won't stop running after.

### ISSUE THREAD

**Issue by itshimbuga** [P0cL4bs/wifipumpkin3#23]
I connected android device to AP then visited google 
went to wifipumkin3 cli and entered "clients" command.
and this happened:

 **wp3 > clients
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 4, in <module>
    __import__('pkg_resources').run_script('wifipumpkin3==1.0.0', 'wifipumpkin3')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/EGG-INFO/scripts/wifipumpkin3", line 103, in <module>
    prompt.cmdloop("Starting prompt...")
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 43, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 149, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__init__.py", line 252, in do_clients
    self.tableUI.ui_table_mod.start()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/ui/table.py", line 157, in start
    self.main()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/ui/table.py", line 144, in main
    self.setup_view()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/ui/table.py", line 138, in setup_view
    self.add_Clients(Refactor.readFileDataToJson(C.CLIENTS_CONNECTED))
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/ui/table.py", line 179, in add_Clients
    data_dict[data]["HOSTNAME"],
KeyError: 'HOSTNAME'
QProcess: Destroyed while process ("/usr/sbin/hostapd") is still running.**

Now when I run wifipumpkin3, AP is already running and can't stop it.
![image](https://user-images.githubusercontent.com/64389512/80531628-fe795980-89ab-11ea-81da-c9c8dfec17f9.png)

* wifipumpkin3 v1.0.0  
* Virtual Machine (yes or no and which): yes
* Operating System: kali
* version: 2020.1

**Comment by jepunband** [comment]
typing 'clients' throws off error ..

Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 11, in <module>
    load_entry_point('wifipumpkin3==1.0.0', 'console_scripts', 'wifipumpkin3')()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__main__.py", line 106, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 43, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 165, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__init__.py", line 259, in do_clients
    self.tableUI.ui_table_mod.start()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/ui/table.py", line 157, in start
    self.main()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/ui/table.py", line 144, in main
    self.setup_view()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/ui/table.py", line 138, in setup_view
    self.add_Clients(Refactor.readFileDataToJson(C.CLIENTS_CONNECTED))
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/platforms.py", line 173, in readFileDataToJson
    datastore = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
