### ISSUE TITLE
AttributeError: 'str' object has no attribute 'pack'

### ISSUE THREAD

**Issue by steveiliop56** [P0cL4bs/wifipumpkin3#238]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

Hello!

I am trying to run wifipumpkin3 on my raspberry pi 4 with a TP-Link Archer T2U PLUS wifi interface. Everything works fine until a client connects to the access point and starts making requests. So when a clients connects I start getting the error ``AttributeError: 'str' object has no attribute 'pack'`` from pydns server I think... 

**To Reproduce**
1. Install wifipumkin3 on raspberry pi with the deb package.
2. Run the getting started commands:
```
set interface wlan1 
set ssid demo
set proxy noproxy
ignore pydns_server
start
```
5. Connect a client to the AP. 
4. See error.

**Expected behavior**
I recently started using wifipumkin3 so I think that the expected behavior should be for the errors from pydns server not appear.

**Screenshots**
Here are the full logs from wifipumpkin3: (Phone info and mac address are replaced with ``somephone`` and ``somemac``)
``` Shellscript
 $ sudo wifipumpkin3

                            .,'
                        .''.'
                        .' .'
            .    ' . ~,'  `.~ . `    .
        . '  .  '   .`:_. . _:'.   `  .  ` .
    .'   .'     ,     .'^'.    .     `.   `.
    .    .       .A.  .     . .A.       .    .
                .d000b.      .d000b.
    '    '    .d0000000b.  .d0000000b.    `    `
    .    .      .      . db  .     .      .    .
                        d00b
    `    `?0o.  `     `     '    '  .o0P'    '
        .    `?00   ooooo.  .ooooo   00P' .   .
        ` .   `?00000P ?0bd0P ?00000P' .' . '
            . . `~~   ~~~~  .~~'  . .
                ~     - ~~ -    ~
                                  codename: Yorixiriamori
by: @mh4x0f - P0cL4bs Team | version: 1.1.5 main
[*] Session id: f907682c-1984-11ee-96ec-d83add1be604
Starting prompt...
wp3 > set interface wlan1
wp3 > set ssid demo
wp3 > set proxy noproxy
wp3 > ignore pydns_server
wp3 > start
[+] enable forwarding in iptables...
[*] sharing internet connection with NAT...
[+] starting hostpad pid: [5601]
wp3 > [+] hostapd is running
[*] starting pydhcp_server
[*] starting pydns_server port: 53
[*] starting sniffkin3 port: [80, 8080]
[+] sniffkin3 -> httpCap    activated
[+] sniffkin3 -> kerberos   activated
[+] sniffkin3 -> hexdump    activated
[+] sniffkin3 -> emails     activated
[+] sniffkin3 -> ftp        activated


 [  pydhcp_server  ] 12:36:41  - RECV from ('0.0.0.0', 68):
::Header::
        op: BOOTREQUEST
        hwmac: MAC('somemac')
        flags:
        hops: 0
        secs: 0
        xid: 1416681763
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('0.0.0.0')
        sname: ''
        file: ''

::Body::
        [ ][012] hostname: 'somephone'
        [-][053] dhcp_message_type: DHCP_DISCOVER
        [-][055] parameter_request_list: 053:dhcp_message_type
        [ ][057] maximum_dhcp_message_size: 1500
        [ ][060] vendor_class_identifier: 'android-dhcp-12'
        [ ][061] client_identifier: [462, 35209, 49073]
        [ ][080] rapid_commit: None

 [  pydhcp_server  ] 12:36:41  - DISCOVER: packet from 10.0.0.21
 [  pydhcp_server  ] 12:36:41  - SEND to ('0.0.0.0', 68):
::Header::
        op: BOOTREPLY
        hwmac: MAC('somemac')
        flags:
        hops: 0
        secs: 0
        xid: 1416681763
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('10.0.0.21')
        sname: ''
        file: ''

::Body::
        [X][001] subnet_mask: IPv4Address('255.0.0.0')
        [ ][012] hostname: 'somephone'
        [X][051] ip_address_lease_time: 7200
        [-][053] dhcp_message_type: DHCP_OFFER
        [X][054] server_identifier: IPv4Address('10.0.0.1')
        [ ][080] rapid_commit: None

 [  pydhcp_server  ] 12:36:41  - RECV from ('0.0.0.0', 68):
::Header::
        op: BOOTREQUEST
        hwmac: MAC('somemac')
        flags:
        hops: 0
        secs: 0
        xid: 1416681763
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('0.0.0.0')
        sname: ''
        file: ''

::Body::
        [ ][012] hostname: 'somephone'
        [ ][050] requested_ip_address: IPv4Address('10.0.0.21')
        [-][053] dhcp_message_type: DHCP_REQUEST
        [X][054] server_identifier: IPv4Address('10.0.0.1')
        [-][055] parameter_request_list: 053:dhcp_message_type, 054:server_identifier
        [ ][057] maximum_dhcp_message_size: 1500
        [ ][060] vendor_class_identifier: 'android-dhcp-12'
        [ ][061] client_identifier: [462, 35209, 49073]

 [  pydhcp_server  ] 12:36:41  - REQUEST: packet from 10.0.0.21 to 10.0.0.1
[*] ce:89:89:bf:b1:b2 client join the AP
 [  pydhcp_server  ] 12:36:41  - SEND to ('0.0.0.0', 68):
::Header::
        op: BOOTREPLY
        hwmac: MAC('somemac')
        flags:
        hops: 0
        secs: 0
        xid: 1416681763
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('10.0.0.21')
        sname: ''
        file: ''

::Body::
        [X][001] subnet_mask: IPv4Address('255.0.0.0')
        [X][003] router: [IPv4Address('10.0.0.1'), IPv4Address('8.8.8.8')]
        [X][006] domain_name_servers: [IPv4Address('10.0.0.1')]
        [ ][012] hostname: 'somephone'
        [X][051] ip_address_lease_time: 7200
        [-][053] dhcp_message_type: DHCP_ACK
        [X][054] server_identifier: IPv4Address('10.0.0.1')

 [  sniffkin3  ] 12:36:42  - [ 10.0.0.21 > 216.58.212.131 ] GET connectivitycheck.gstatic.com/generate_204
----------------------------------------
Exception occurred during processing of request from ('10.0.0.21', 57969)
----------------------------------------
Exception occurred during processing of request from ('10.0.0.21', 43432)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/dist-packages/dnslib/server.py", line 147, in handle
    rdata = self.get_reply(data)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/server.py", line 164, in get_reply
    reply = resolver.resolve(request,self)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/packets/dnsserver.py", line 169, in resolve
    return super().resolve(request, handler)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/server.py", line 147, in handle
    rdata = self.get_reply(data)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/proxy.py", line 40, in resolve
    proxy_r = request.send(self.address,self.port,
  File "/usr/local/lib/python3.9/dist-packages/dnslib/server.py", line 164, in get_reply
    reply = resolver.resolve(request,self)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 354, in send
    data = self.pack()
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/packets/dnsserver.py", line 169, in resolve
    return super().resolve(request, handler)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/proxy.py", line 40, in resolve
    proxy_r = request.send(self.address,self.port,
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 321, in pack
    rr.pack(buffer)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 354, in send
    data = self.pack()
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 874, in pack
    self.rdata.pack(buffer)
AttributeError: 'str' object has no attribute 'pack'
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 321, in pack
    rr.pack(buffer)
----------------------------------------
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 874, in pack
    self.rdata.pack(buffer)
AttributeError: 'str' object has no attribute 'pack'
----------------------------------------
 [  sniffkin3  ] 12:36:46  - [ 10.0.0.21 > 142.250.185.100 ] GET www.google.com/gen_204
----------------------------------------
Exception occurred during processing of request from ('10.0.0.21', 57969)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/dist-packages/dnslib/server.py", line 147, in handle
    rdata = self.get_reply(data)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/server.py", line 164, in get_reply
    reply = resolver.resolve(request,self)
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/packets/dnsserver.py", line 169, in resolve
    return super().resolve(request, handler)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/proxy.py", line 40, in resolve
    proxy_r = request.send(self.address,self.port,
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 354, in send
    data = self.pack()
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 321, in pack
    rr.pack(buffer)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 874, in pack
    self.rdata.pack(buffer)
AttributeError: 'str' object has no attribute 'pack'
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('10.0.0.21', 43432)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/dist-packages/dnslib/server.py", line 147, in handle
    rdata = self.get_reply(data)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/server.py", line 164, in get_reply
    reply = resolver.resolve(request,self)
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/packets/dnsserver.py", line 169, in resolve
    return super().resolve(request, handler)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/proxy.py", line 40, in resolve
    proxy_r = request.send(self.address,self.port,
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 354, in send
    data = self.pack()
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 321, in pack
    rr.pack(buffer)
  File "/usr/local/lib/python3.9/dist-packages/dnslib/dns.py", line 874, in pack
    self.rdata.pack(buffer)
AttributeError: 'str' object has no attribute 'pack'
----------------------------------------
 [  sniffkin3  ] 12:36:53  - [ 10.0.0.21 > 216.58.212.131 ] GET connectivitycheck.gstatic.com/generate_204
 [  sniffkin3  ] 12:36:56  - [ 10.0.0.21 > 142.250.185.100 ] GET www.google.com/gen_204
 [  sniffkin3  ] 12:37:05  - [ 10.0.0.21 > 216.58.212.131 ] GET connectivitycheck.gstatic.com/generate_204
 [  sniffkin3  ] 12:37:08  - [ 10.0.0.21 > 142.250.185.100 ] GET www.google.com/gen_204
 [  sniffkin3  ] 12:37:19  - [ 10.0.0.21 > 216.58.212.131 ] GET connectivitycheck.gstatic.com/generate_204
 [  sniffkin3  ] 12:37:22  - [ 10.0.0.21 > 142.250.185.100 ] GET www.google.com/gen_204
 [  sniffkin3  ] 12:37:37  - [ 10.0.0.21 > 216.58.212.131 ] GET connectivitycheck.gstatic.com/generate_204
 [  sniffkin3  ] 12:37:40  - [ 10.0.0.21 > 142.250.185.100 ] GET www.google.com/gen_204
 [  sniffkin3  ] 12:37:48  - [ 10.0.0.21 > 192.73.248.83 ] GET derp9e.tailscale.com/generate_204
[*] somemac client has left AP
stop
[*] thread sniffkin3 successfully stopped
[*] thread pydhcp_server successfully stopped
[*] thread hostapd_static successfully stopped
[*] thread pydhcp_server successfully stopped
wp3 > exit
Exiting..
```

**Desktop (please complete the following information):** Raspberry Pi 4
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `). wifipumpkin3 v1.1.5 branch: main
* Virtual Machine (yes or no and which):  no
* Operating System: Raspberry Pi OS 64bit
* version: 11 Bullseye (Python 3.9.2)

**INCOMPLETE REPORT WILL BE CLOSED**

**Comment by mh4x0f** [comment]
check the version of dnslib from terminal:
pip3 freeze | grep dnslib

**Comment by steveiliop56** [comment]
Ok, here is the result:

```Python
dnslib==0.9.23
dnspython==2.0.0
```

**Comment by mh4x0f** [comment]
ok fist, try to install the version dnspython==1.16.0.
sudo pip3 install dnspython==1.16.0

if not working try that:

and try to start again the AP if you got have error maybe the solution is come back the version dnslib to dnslib==0.9.17
sudo pip3 install dnslib==0.9.17

**Comment by steveiliop56** [comment]
Ok I reinstalled wifi pumpkin (because I needed to reinstall the os on the raspberry pi) and now I am getting and other error imidiately after trying to start it up:

```
/usr/bin/wifipumpkin3:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Traceback (most recent call last):
  File "/usr/bin/wifipumpkin3", line 11, in <module>
    load_entry_point('wifipumpkin3==1.1.5', 'console_scripts', 'wifipumpkin3')()  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line
536, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line
2931, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line
2518, in load
    return self.resolve()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line
2524, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/wifipumpkin3/__main__.py", line 22, in <module>
    from wifipumpkin3.core.servers.rest.application import RestControllerAPI
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/servers/rest/application.py", line 1, in <module>
    from flask import Flask
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
```

**Comment by mh4x0f** [comment]
try that sudo pip install Flask==2.1.0

**Comment by steveiliop56** [comment]
And... Error again:

```
/usr/bin/wifipumpkin3:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Traceback (most recent call last):
  File "/usr/bin/wifipumpkin3", line 11, in <module>
    load_entry_point('wifipumpkin3==1.1.5', 'console_scripts', 'wifipumpkin3')()  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line
536, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line
2931, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line
2518, in load
    return self.resolve()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line
2524, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/wifipumpkin3/__main__.py", line 22, in <module>
    from wifipumpkin3.core.servers.rest.application import RestControllerAPI
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/servers/rest/application.py", line 2, in <module>
    from wifipumpkin3.core.servers.rest.ext import configuration
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/servers/rest/ext/configuration.py", line 2, in <module>
    from wifipumpkin3.core.servers.rest.blueprints import restapi
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/servers/rest/blueprints/restapi/__init__.py", line 2, in <module>
    from flask_restful import Resource, Api
  File "/usr/lib/python3/dist-packages/flask_restful/__init__.py", line 14, in <module>
    from flask.helpers import _endpoint_from_view_func
ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers'
(/usr/local/lib/python3.9/dist-packages/flask/helpers.py)
```

**Comment by mh4x0f** [comment]
try that sudo pip3 install Flask-RESTful==0.3.9

**Comment by steveiliop56** [comment]
Ok, so it seems to work now, I didn't get any errors and the AP worked fine. So I am closing the issue although there wasn't exactly a solution. I believe that the error was either in the flask packages or it was interfering with something on my old installation...

**Comment by mh4x0f** [comment]
@steveiliop56  check the version of dnslib and dnspython from terminal again:
pip3 freeze | grep dns

**Comment by steveiliop56** [comment]
Yeahh it's kind of hard for me now but as I can see from the requirements.txt you have set it to this:

```
dnslib==0.9.17  
dnspython==1.16.0
```

My only concern is that the release ``.deb`` file that most user use (including me) is five months old. So will it use the newer requirements?

**Comment by mh4x0f** [comment]
i cant reproduce this bug on my environment with the same dependencies installed.  

btw, I 'll closed if another user got this bug, maybe the option is repoen and try to replicate again.
