### ISSUE TITLE
Please fix this Error

### ISSUE THREAD

**Issue by ClonicalClone** [P0cL4bs/wifipumpkin3#239]
wp3 > start
[+] enable forwarding in iptables...
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.1.5', 'console_scripts', 'wifipumpkin3')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifipumpkin3-1.1.5-py3.11.egg/wifipumpkin3/__main__.py", line 257, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/local/lib/python3.11/dist-packages/wifipumpkin3-1.1.5-py3.11.egg/wifipumpkin3/core/common/terminal.py", line 122, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.11/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifipumpkin3-1.1.5-py3.11.egg/wifipumpkin3/core/common/terminal.py", line 88, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.11/cmd.py", line 217, in onecmd
    return func(arg)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifipumpkin3-1.1.5-py3.11.egg/wifipumpkin3/core/common/console.py", line 231, in do_start
    if self.wireless_controller.Start() != None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifipumpkin3-1.1.5-py3.11.egg/wifipumpkin3/core/controllers/wirelessmodecontroller.py", line 71, in Start
    self.Activated.Start()
  File "/usr/local/lib/python3.11/dist-packages/wifipumpkin3-1.1.5-py3.11.egg/wifipumpkin3/core/wirelessmode/wirelessmode.py", line 108, in Start
    self.Initialize()
  File "/usr/local/lib/python3.11/dist-packages/wifipumpkin3-1.1.5-py3.11.egg/wifipumpkin3/core/wirelessmode/static.py", line 53, in Initialize
    if not (self.Settings.checkNetworkAP()):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifipumpkin3-1.1.5-py3.11.egg/wifipumpkin3/core/wirelessmode/static.py", line 237, in checkNetworkAP
    raise InterfaceBuzyError(
wifipumpkin3.exceptions.errors.networkException.InterfaceBuzyError: Wireless interface is busy : Device wlan0 is busy 
 Connection has been detected, joined the correct Wi-Fi network
Device or resource busy
You may need to another Wi-Fi USB adapter
for create AP or try use with local connetion(Ethernet).

**Comment by ClonicalClone** [comment]
Please solve this
