### ISSUE TITLE
error trying to set to noproxy

### ISSUE THREAD

**Issue by itshimbuga** [P0cL4bs/wifipumpkin3#24]
1. I ran sudo wifipumpkin3 -wlan1
2. I ran 'ap' command
3. then I ran 'proxys' command
4. then I tried setting it to noproxy

**wp3 > set noproxy true
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 11, in <module>
    load_entry_point('wifipumpkin3==1.0.0', 'console_scripts', 'wifipumpkin3')()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__main__.py", line 102, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 43, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 149, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__init__.py", line 394, in do_set
    return getattr(self.parser_list_func[func], func)(value, args)
AttributeError: 'NoProxy' object has no attribute 'parser_set_noproxy'**

![image](https://user-images.githubusercontent.com/64389512/80547240-ca606180-89c8-11ea-9099-aa990104c094.png)

* wifipumpkin3 v1.0.0
* Virtual Machine (yes or no and which):  yes
* Operating System: kali
* version: 2020.1

**Comment by mh4x0f** [comment]
this is a bug, but the correct syntax to set noproxy is:
``` bash
set proxy noproxy 
```
