### ISSUE TITLE
Error while create  rogue access point attack

### ISSUE THREAD

**Issue by misbagas** [P0cL4bs/wifipumpkin3#253]
I try to run this on my kali linux to make Rogue access point attack

```
`┌──(misbahskuy㉿kali)-[~]
└─$ sudo wifipumpkin3

                            .,'
                        .''.'
                        .' .'
            _.ood0Pp._ ,'  `.~ .q?00doo._
        .od00Pd0000Pdb._. . _:db?000b?000bo.
     .?000Pd0000Pd0000PdbMb?0000b?000b?0000b.
    .d0000Pd0000Pd0000Pd0000b?0000b?000b?0000b.
    d0000Pd0000Pd00000Pd0000b?00000b?0000b?000b.
    00000Pd0000Pd0000Pd00000b?00000b?0000b?0000b
    ?0000b?0000b?  WiFiPumpkin3  00Pd0000Pd0000P
    ?0000b?0000b?0000b?00000Pd00000Pd0000Pd000P
    `?0000b?0000b?0000b?0000Pd0000Pd0000Pd000P'
     `?000b?0000b?000b?0000Pd000Pd0000Pd000P
        `~?00b?000b?000b?000Pd00Pd000Pd00P'
            `~?0b?0b?000b?0Pd0Pd000PdP~'
                                     codename: Gao
by: @mh4x0f - P0cL4bs Team | version: 1.1.7 main
[*] Session id: 5aa3cea6-9f25-11ee-9bfc-0800271e765e 
wp3 > set interface wlan0
wp3 > set ssid Free Wifi
wp3 > set proxy noproxy
wp3 > ignore pydns_server
wp3 > start
[+] enable forwarding in iptables...
Traceback (most recent call last):
  File "/usr/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.1.7', 'console_scripts', 'wifipumpkin3')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wifipumpkin3/__main__.py", line 257, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/common/terminal.py", line 136, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.11/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/common/terminal.py", line 92, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.11/cmd.py", line 217, in onecmd
    return func(arg)
           ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/common/console.py", line 233, in do_start
    if self.wireless_controller.Start() != None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/controllers/wirelessmodecontroller.py", line 71, in Start
    self.Activated.Start()
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/wirelessmode/wirelessmode.py", line 108, in Start
    self.Initialize()
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/wirelessmode/static.py", line 53, in Initialize
    if not (self.Settings.checkNetworkAP()):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wifipumpkin3/core/wirelessmode/static.py", line 231, in checkNetworkAP
    raise ApModeSupportError(
wifipumpkin3.exceptions.errors.networkException.ApModeSupportError: [Error] AP mode : wlan0 ap mode not found! 
 failed AP mode: warning interface, the feature
Access point mode is not supported by this device above.
Your adapter does not support for create Access Point Network.
`
```

this is my ifconfig

```
┌──(misbahskuy㉿kali)-[~]
└─$ ifconfig 
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.11  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::a00:27ff:fe1e:765e  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:1e:76:5e  txqueuelen 1000  (Ethernet)
        RX packets 40588  bytes 51904935 (49.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11683  bytes 854168 (834.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4  bytes 240 (240.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 240 (240.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=803<UP,BROADCAST,NOTRAILERS,PROMISC,ALLMULTI>  mtu 1400
        inet 10.0.0.1  netmask 255.0.0.0  broadcast 10.255.255.255
        unspec CE-69-77-A2-C9-EE-00-61-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 62:fb:bd:38:96:2d  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan2: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 5e:57:41:6a:9c:83  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


```

this is my kali linux version
`Linux kali 6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux`

**Comment by misbagas** [comment]
@mh4x0f please help me to solve this first

**Comment by misbagas** [comment]
@mh4x0f I was plug my wireless adapter but it's no work
