### ISSUE TITLE
Post installation problem - wifipumpkin3 won't run

### ISSUE THREAD

**Issue by pispuso** [P0cL4bs/wifipumpkin3#26]
The installation of wifipumpkin3 went great... or at least that what i thought. No problems at all on the installation. After trying to run wifipumpkin3 I got this error:

Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 11, in <module>
    load_entry_point('wifipumpkin3==1.0.0', 'console_scripts', 'wifipumpkin3')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__init__.py", line 1, in <module>
    from wifipumpkin3.core.common.terminal import ConsoleUI
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 7, in <module>
    from wifipumpkin3.core.common.platforms import Linux
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/platforms.py", line 9, in <module>
    from scapy.all import *
  File "/usr/lib/python3/dist-packages/scapy/all.py", line 18, in <module>
    from scapy.arch import *
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 56, in <module>
    from scapy.arch.linux import *  # noqa F403
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 29, in <module>
    from scapy.packet import Packet, Padding
  File "/usr/lib/python3/dist-packages/scapy/packet.py", line 29, in <module>
    from scapy.extlib import PYX
  File "/usr/lib/python3/dist-packages/scapy/extlib.py", line 21, in <module>
    from matplotlib import get_backend as matplotlib_get_backend
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 207, in <module>
    _check_versions()
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 202, in _check_versions
    if LooseVersion(module.__version__) < minver:
AttributeError: module 'numpy' has no attribute '__version__'

-------------------------------

Probably is nothing to do with wifipumkin3 specifically but I don't know how to resolve this and maybe someone can guide me to find a solution.

**To Reproduce**
Just installed it without errors.
Tried to run it, got the error. All needed tools are already installed.

Python 3.7.7 installed and selected.

**Desktop (please complete the following information):**
* Wifipumpkin3 1.0.0
* Virtual Machine (yes or no and which): No
* Operating System: Kali Rolling Fully Updated
* version: 2020.2

Thanks!

**Comment by pispuso** [comment]
Fixed it! I'll just leave this if anyone else encounters the same problem.

As the error log says, it was a numpy problem. I first tried to uninstall and reinstall it using:
```
$ pip uninstall -y numpy
$ pip uninstall -y setuptools
$ pip install setuptools
$ pip install numpy
```

But got it to run using this workaround:
```
python3 -m pip uninstall -y numpy
python3 -m pip uninstall -y setuptools
python3 -m pip install setuptools
python3 -m pip install numpy
```

After that it starts without problems.
