### ISSUE TITLE
Crash after joinin ap - basic configuration

### ISSUE THREAD

**Issue by Pascal66** [P0cL4bs/wifipumpkin3#48]
**Description of the bug or feature request**
```
wp3 > start
[+] enable forwarding in iptables...
[*] sharing internet connection with NAT...
[+] starting hostpad pid: [21600]
[*] starting pydhcp_server
[*] starting pydns_server
[+] starting pumpkinproxy pid: [21606]
[*] starting sniffkin3 port: [80, 8080]
wp3 > [+] sniffkin3 -> kerberos   activated
[+] sniffkin3 -> httpCap    activated
[+] sniffkin3 -> hexdump    activated
[+] sniffkin3 -> ftp        activated
[+] sniffkin3 -> emails     activated


 [  pydns_server  ] 10:21:20  - loading zone file "/root/.config/wifipumpkin3/config/app/dns_hosts.ini": 
 [  pydns_server  ] 10:21:20  -   1: example.com.            300     IN      A       10.0.0.1 
 [  pydns_server  ] 10:21:20  -   2: example.com.            300     IN      CNAME   whatever.com. 
 [  pydns_server  ] 10:21:21  -   3: example.com.            300     IN      MX      5 whatever.com. 
 [  pydns_server  ] 10:21:21  -   4: example.com.            300     IN      MX      10 mx2.whatever.com. 
 [  pydns_server  ] 10:21:21  -   5: example.com.            300     IN      MX      20 mx3.whatever.com. 
 [  pydns_server  ] 10:21:21  -   6: example.com.            86400   IN      NS      ns1.whatever.com. 
 [  pydns_server  ] 10:21:21  -   7: example.com.            86400   IN      NS      ns2.whatever.com. 
 [  pydns_server  ] 10:21:21  -   8: example.com.            300     IN      TXT     "hello this is some text" 
 [  pydns_server  ] 10:21:21 -   9: example.com.            86400   IN      SOA     ns1.example.com. dns.example.com. 1591437803 3600 10800 86400 3600 
 [  pydns_server  ] 10:21:21  -  10: testing.com.            300     IN      TXT     "one long value: IICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgFWZUed1qcBziAsqZ/LzT2ASxJYuJ5sko1CzWFhFuxiluNnwKjSknSjanyYnm0vro4dhAtyiQ7OPVROOaNy9Iyklvu91KuhbYi6l80Rrdnuq1yjM//xjaB6DGx8+m1ENML8PEdSFbKQbh9akm2bkNw5DC5a8Slp7j+eEVHkgV3k3oRhkPcrKyoPVvniDNH+Ln7DnSGC" "+Aw5Sp+fhu5aZmoODhhX5/1mANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA26JaFWZUed1qcBziAsqZ/LzTF2ASxJYuJ5sk" 
 [  pydns_server  ] 10:21:21  - 10 zone resource records generated from zone file 
 [  pydhcp_server  ] 10:21:49  - RECV from ('0.0.0.0', 68):
::Header::
        op: BOOTREQUEST
        hwmac: MAC('28:3f:69:1f:ad:8d')
        flags: 
        hops: 0
        secs: 0
        xid: 1085634069
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('0.0.0.0')
        sname: ''
        file: ''

::Body::
        [-][053] dhcp_message_type: DHCP_DISCOVER
        [-][055] parameter_request_list: 053:dhcp_message_type
        [ ][057] maximum_dhcp_message_size: 1500
        [ ][060] vendor_class_identifier: 'android-dhcp-8.0.0'
 
 [  pydhcp_server  ] 10:21:49  - DISCOVER: packet from 10.0.0.21 
 [  pydhcp_server  ] 10:21:53  - SEND to ('0.0.0.0', 68):
::Header::
        op: BOOTREPLY
        hwmac: MAC('28:3f:69:1f:ad:8d')
        flags: 
        hops: 0
        secs: 0
        xid: 1085634069
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('10.0.0.21')
        sname: ''
        file: ''

::Body::
        [X][001] subnet_mask: IPv4Address('255.0.0.0')
        [X][051] ip_address_lease_time: 7200
        [-][053] dhcp_message_type: DHCP_OFFER
        [X][054] server_identifier: IPv4Address('10.0.0.1')
 
 [  pydhcp_server  ] 10:21:53  - RECV from ('0.0.0.0', 68):
::Header::
        op: BOOTREQUEST
        hwmac: MAC('28:3f:69:1f:ad:8d')
        flags: 
        hops: 0
        secs: 0
        xid: 1085634069
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('0.0.0.0')
        sname: ''
        file: ''

::Body::
        [ ][050] requested_ip_address: IPv4Address('10.0.0.21')
        [-][053] dhcp_message_type: DHCP_REQUEST
        [X][054] server_identifier: IPv4Address('10.0.0.1')
        [-][055] parameter_request_list: 053:dhcp_message_type, 054:server_identifier
        [ ][057] maximum_dhcp_message_size: 1500
        [ ][060] vendor_class_identifier: 'android-dhcp-8.0.0'
 
 [  pydhcp_server  ] 10:21:53  - REQUEST: packet from 10.0.0.21 to 10.0.0.1 
[*] 28:3f:69:1f:ad:8d client join the AP 
 [  pydhcp_server  ] 10:21:56  - SEND to ('0.0.0.0', 68):
::Header::
        op: BOOTREPLY
        hwmac: MAC('28:3f:69:1f:ad:8d')
        flags: 
        hops: 0
        secs: 0
        xid: 1085634069
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('10.0.0.21')
        sname: ''
        file: ''

::Body::
        [X][001] subnet_mask: IPv4Address('255.0.0.0')
        [X][003] router: [IPv4Address('10.0.0.1'), IPv4Address('8.8.8.8')]
        [X][006] domain_name_servers: [IPv4Address('10.0.0.1')]
        [X][051] ip_address_lease_time: 7200
        [-][053] dhcp_message_type: DHCP_ACK
        [X][054] server_identifier: IPv4Address('10.0.0.1')
 
 [  pydhcp_server  ] 10:21:56  - RECV from ('0.0.0.0', 68):
::Header::
        op: BOOTREQUEST
        hwmac: MAC('28:3f:69:1f:ad:8d')
        flags: 
        hops: 0
        secs: 0
        xid: 1085634069
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('0.0.0.0')
        sname: ''
        file: ''

::Body::
        [ ][050] requested_ip_address: IPv4Address('10.0.0.21')
        [-][053] dhcp_message_type: DHCP_REQUEST
        [X][054] server_identifier: IPv4Address('10.0.0.1')
        [-][055] parameter_request_list: 053:dhcp_message_type, 054:server_identifier
        [ ][057] maximum_dhcp_message_size: 1500
        [ ][060] vendor_class_identifier: 'android-dhcp-8.0.0'
 
 [  pydhcp_server  ] 10:21:57  - REQUEST: packet from 10.0.0.21 to 10.0.0.1 
[*] 28:3f:69:1f:ad:8d client join the AP 
 [  pydns_server  ] 10:21:57  - no local zone found, proxying captive.apple.com.[A] 
 [  pydns_server  ] 10:21:57  - no local zone found, proxying developers.google.cn.[A] 
 [  pydns_server  ] 10:21:57  - no local zone found, proxying alt1-mtalk.google.com.[A] 
 [  pydns_server  ] 10:21:57  - no local zone found, proxying mqtt-mini.facebook.com.[A] 
 [  pydns_server  ] 10:21:57  - no local zone found, proxying www.google.com.[A] 
 [  pydns_server  ] 10:21:57  - no local zone found, proxying amdcopen.m.taobao.com.[A] 
 [  pydns_server  ] 10:21:58  - no local zone found, proxying play.googleapis.com.[A] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/threads.py", line 196, in read_OutputCommand
    self.removeInactivityClient(self.data.split()[2])
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/threads.py", line 185, in removeInactivityClient
    all_clients = Refactor.readFileDataToJson(C.CLIENTS_CONNECTED)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/platforms.py", line 173, in readFileDataToJson
    datastore = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Aborted

```

**To Reproduce**
3. See error

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).
wifipumpkin3 v1.0.5
* Operating System: Kali
* version: OOT_IMAGE=/live/vmlinuz-5.5.0-kali2-amd64

**Comment by mh4x0f** [comment]
did you try run the `wp3` again ? maybe this is a bug temporary.

**Comment by Pascal66** [comment]
@mh4x0f Thank you, i'll try again.

**Comment by mh4x0f** [comment]
@Pascal66 the error is persist ?

**Comment by Pascal66** [comment]
I'll tell you tomorrow with another fresh install and another test
