### ISSUE TITLE
Can't get captivePortal running - pydns_server Error

### ISSUE THREAD

**Issue by biejay** [P0cL4bs/wifipumpkin3#49]
**Wifipumpkin v1.0.5
VmWareWorkstation Pro 15.5.2
Kali 2020.2**

Trying to run **captiveflask with loginPage** but when i connect my devices then i can just surf the internet and **no captiveportal opens**. 
My guess is, that the following error log could cause it:

```

[  pydns_server  ] 14:15:16  - no local zone found, proxying .[A] 
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/dist-packages/dnslib-0.9.13-py3.8.egg/dnslib/server.py", line 147, in handle
    rdata = self.get_reply(data)
  File "/usr/local/lib/python3.8/dist-packages/dnslib-0.9.13-py3.8.egg/dnslib/server.py", line 164, in get_reply
    reply = resolver.resolve(request,self)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/packets/dnsserver.py", line 167, in resolve
    return super().resolve(request, handler)
  File "/usr/local/lib/python3.8/dist-packages/dnslib-0.9.13-py3.8.egg/dnslib/proxy.py", line 40, in resolve
    proxy_r = request.send(self.address,self.port,
  File "/usr/local/lib/python3.8/dist-packages/dnslib-0.9.13-py3.8.egg/dnslib/dns.py", line 353, in send
    data = self.pack()
  File "/usr/local/lib/python3.8/dist-packages/dnslib-0.9.13-py3.8.egg/dnslib/dns.py", line 320, in pack
    rr.pack(buffer)
  File "/usr/local/lib/python3.8/dist-packages/dnslib-0.9.13-py3.8.egg/dnslib/dns.py", line 869, in pack
    self.rdata.pack(buffer)
AttributeError: 'str' object has no attribute 'pack'

```

**Comment by mh4x0f** [comment]
hi, download and reinstall the tool `sudo python3 setup.py install `, will be solve the problem.

**Comment by biejay** [comment]
Did reinstall but still no luck.

also got this error:

```
[  captiveflask  ] 16:26:54  - Traceback (most recent call last):
  File "/usr/local/bin/captiveflask", line 4, in <module>
    __import__('pkg_resources').run_script('wifipumpkin3==1.0.5', 'captiveflask')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/captiveflask' not found in metadata at '/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.5.dist-info'

```

**Comment by mh4x0f** [comment]
execute this:
``` sh
sudo pip3 uninstall wifipumpkin3==1.0.5
sudo make clean
sudo python3 setup.py install
```
