### ISSUE TITLE
error versionconflict asn1crypto

### ISSUE THREAD

**Issue by sh1va73** [P0cL4bs/wifipumpkin3#50]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**
error when start tool

**To Reproduce**

sudo wifipumkin3

error:

sudo wifipumpkin3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (asn1crypto 0.24.0 (/usr/lib/python3/dist-packages), Requirement.parse('asn1crypto>=1.0.0'), {'oscrypto'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3258, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (asn1crypto 0.24.0 (/usr/lib/python3/dist-packages), Requirement.parse('asn1crypto>=1.0.0'), {'oscrypto'})

**Expected behavior**
normal start of tool

**Screenshots**

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `). > if i check I get same error
* Virtual Machine (yes or no and which): no
* Operating System: Kali
* version: 2020.2

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by Sh4kim** [comment]
Hello, I had the same problem. This is more an issue with pip than wifipumkin.
pip just don't want to delet something that is not in his folder.
I think the best option is to delet every asn1crypto files before installing again:

First use pip to remove all asn1crypto package:
`pip uninstall asn1crypto`

Then search and delet by hands all asn1crypto folders left . You can use:
`locate asn1crypto `
most of the time you will have to delet:

- /usr/lib/python2.7/dist-packages/asn1crypto
- /usr/lib/python3/dist-packages/asn1crypto
-/usr/local/lib/python3.8/dist-packages/asn1crypto-xxxx

Remove all thoses folders using rm -r. For exemple:
`rm -r /usr/lib/python2.7/dist-packages/asn1crypto`

then install asn1crypto again, you can use:
`pip install -r requirements.txt` in the wifipumpkin3 folder

 Or install it directly:
`pip install asn1crypto`

Hope that help.

**Comment by sh1va73** [comment]
Thanks for the help. I followed each step but in the end I got the same error again.

**Comment by sh1va73** [comment]
Now i tried again and I have a new error:

ModuleNotFoundError: No module named 'PyQt5.QtCore'

But when i check then requirement is already satisfied.
