### ISSUE TITLE
no module named PyQt5.QtCore

### ISSUE THREAD

**Issue by sh1va73** [P0cL4bs/wifipumpkin3#51]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

**To Reproduce**

install wifipumpkin3 as instructed
run wifipumpkin3

I get this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 11, in <module>
    load_entry_point('wifipumpkin3==1.0.5', 'console_scripts', 'wifipumpkin3')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.5-py3.7.egg/wifipumpkin3/__init__.py", line 1, in <module>
    from wifipumpkin3.core.common.console import PumpkinShell
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.5-py3.7.egg/wifipumpkin3/core/common/console.py", line 1, in <module>
    from wifipumpkin3.core.common.terminal import ConsoleUI
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.5-py3.7.egg/wifipumpkin3/core/common/terminal.py", line 3, in <module>
    from wifipumpkin3.core.utility.collection import SettingsINI
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.5-py3.7.egg/wifipumpkin3/core/utility/collection.py", line 2, in <module>
    from PyQt5.QtCore import QSettings
ModuleNotFoundError: No module named 'PyQt5.QtCore'
```

I checked my system and PyQt5 is already installed.
I checked:
python3 -c "from PyQt5.QtCore import QSettings; print('done')"
this is the result:
done

**Expected behavior**
normal start of tool

**Screenshots**

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `). > gives me same error
* Virtual Machine (yes or no and which): no
* Operating System: Kali Linux
* version: 2020.2

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by sh1va73** [comment]
Its working but i dont know how i exactly fixed. I reinstalled everything (also PyQt5)  like on the wiki page and then no more errors.
