### ISSUE TITLE
Dhcp issue

### ISSUE THREAD

**Issue by Pascal66** [P0cL4bs/wifipumpkin3#54]
```
wp3 > start
[+] enable forwarding in iptables...
[*] enable security authentication wireless
[*] sharing internet connection with NAT...
[+] starting hostpad pid: [30263]
[*] starting pydhcp_server
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/packets/dnsserver.py", line 271, in run
    self.tcp_server = DNSServer(
  File "/usr/local/lib/python3.8/dist-packages/dnslib-0.9.7-py3.8.egg/dnslib/server.py", line 343, in __init__
    self.server = server((address,port),handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Aborted

```

**Comment by harames2001** [comment]
Look for open sockets
`lsof -i :80`
and kill the open processes via
`kill <PID>`
