### ISSUE TITLE
_ctypes Module not found 

### ISSUE THREAD

**Issue by syedaqeel** [P0cL4bs/wifipumpkin3#64]
I am using :
```
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.2
```
With Python Version:  Python 3.8.3 
ctypes modules downloaded 
```
python 
Python 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> 
```
When i run:  `python3 setup.py install` it give me following error 

```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools import windows_support
  File "/usr/local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

```
The file "usr/local/lib/python3.8/ctypes/__init__.py" starts like 

```
"""create and manipulate C data types in Python"""

import os as _os, sys as _sys

__version__ = "1.1.0"

from _ctypes import Union, Structure, Array
from _ctypes import _Pointer
from _ctypes import CFuncPtr as _CFuncPtr
from _ctypes import __version__ as _ctypes_version
from _ctypes import RTLD_LOCAL, RTLD_GLOBAL
from _ctypes import ArgumentError

``

**Comment by mh4x0f** [comment]
doc: https://wifipumpkin3.github.io/docs/getting-started#installation
