### ISSUE TITLE
Error Whe Starting CaptiveFlask...

### ISSUE THREAD

**Issue by mrex303** [P0cL4bs/wifipumpkin3#72]
alittle help would be greatly appreciated! when i go to launch/start wifipumpkin it gives me this error. and it happens for all proxies selected aswell. anyone know why or what I can do to fix this? thank you.

wp3 > start
[+] enable forwarding in iptables...
[*] sharing internet connection with NAT...
[*] settings for captive portal:
[*] allow FORWARD UDP DNS
[*] allow traffic to captive portal
[*] block all other traffic in access point
[*] redirecting HTTP traffic to captive portal
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 11, in <module>
    load_entry_point('wifipumpkin3==1.0.7', 'console_scripts', 'wifipumpkin3')()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/__main__.py", line 106, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 44, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 166, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/console.py", line 216, in do_start
    ctr_instance.Start()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/controllers/dhcpcontroller.py", line 41, in Start
    self.Active.Start()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/servers/dhcp/dhcp.py", line 81, in Start
    self.prereq()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/servers/dhcp/dhcp.py", line 65, in prereq
    raise DHCPServerSettingsError(
wifipumpkin3.exceptions.errors.dhcpException.DHCPServerSettingsError: DHCPServer : dhcp same ip range address  
 The DHCPServer is configured with same range ip class, 
it works, but not share internet connection in some case.

QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
Exception ignored in: <function WorkerProcess.__del__ at 0x7fbf65500670>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/threads.py", line 237, in __del__
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.__del__ at 0x7fbf65500670>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/threads.py", line 237, in __del__
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.__del__ at 0x7fbf65500670>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/threads.py", line 237, in __del__
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.__del__ at 0x7fbf65500670>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/threads.py", line 237, in __del__
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.__del__ at 0x7fbf65500670>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/threads.py", line 237, in __del__
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.__del__ at 0x7fbf65500670>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/threads.py", line 237, in __del__
RuntimeError: wrapped C/C++ object of type QProcess has been deleted

and then it closes wifipumpkin and brings me back to prompt.

**Comment by mh4x0f** [comment]
> wifipumpkin3.exceptions.errors.dhcpException.DHCPServerSettingsError: DHCPServer : dhcp same ip range address
The DHCPServer is configured with same range ip class,
it works, but not share internet connection in some case.

this is a error of DHCP Settings, you need to change the default configuration  look:
https://wifipumpkin3.github.io/docs/configuration/configuration-file#dhcp-server-configuration

**Comment by Avatar-TLA** [comment]
Can you explain a bit more about what to check and change?
I have the same issue. I checked the config.ini file, and the dhcp and dhcpdefault setting are the same as you provide in your manual, and also the same settings with another machine i have that works, and not getting that error.
