### ISSUE TITLE
Error after downloading extra captiveflask

### ISSUE THREAD

**Issue by Avatar-TLA** [P0cL4bs/wifipumpkin3#73]
Hello.

I am new to this, but i am pretty sure i searched everything i could find to troubleshoot this issue.

I am using a **raspberry pi 4B** with latest **kali linux version 2020.3**. I had the issue though even before updating (on kali 2020.2 i believe).

After a clean install, i installed **wifipumpkin3 v.1.0.7** and i wanted to test the facebook template.
I followed the instructions of your youtube video (Facebook captive login templates with wifipumpkin3 - https://youtu.be/0TPWLZ8_-mM ) and when i run **list** (_video timestamp 0:42_) i get the following traceback and error at the end, and the wifipumpkin3 crashes.

```
wp3 : extra_captiveflask > list
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/__main__.py", line 106, in main
    prompt.cmdloop("Starting prompt...")
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 44, in cmdloop
    super(ConsoleUI, self).cmdloop(intro="")
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 166, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/console.py", line 185, in do_use
    return module.cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 342, in onecmd
    Cmd.onecmd(self, command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/modules/misc/extra_captiveflask.py", line 69, in do_list
    plugins_installed = self.config_default.get_all_childname("plugins")
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/utility/collection.py", line 64, in get_all_childname
    return [x.split("/")[1] for x in self.get_all_keys() if x.split("/")[0] == key]
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/utility/collection.py", line 76, in get_all_keys
    return self.psettings.allKeys()
AttributeError: 'SettingsINI' object has no attribute 'psettings'
```
That should saw me the list of custom CaptiveFlask.

Is it possible that the raspberry might be the error reason?
Am planning to execute the same thing on a laptop tomorrow, i will notice you about my results.

**Thanks in advance.**

**Comment by Avatar-TLA** [comment]
Hello again.
I tried the same installation on a clean Kali 2020.3 setup on a vmware machine, and i get the same error when i run **list** after i download the templates (following your instructions from the youtube video).

**Comment by mh4x0f** [comment]
You need to change the local path to current directory of **wp3**, go to the directory when you make download and execute the command again.

**Comment by jaykali** [comment]
> You need to change the local path to current directory of **wp3**, go to the directory when you make download and execute the command again.

Can you please tell me how to do this?

**Comment by leandro8687** [comment]
> Hello again. I tried the same installation on a clean Kali 2020.3 setup on a vmware machine, and i get the same error when i run **list** after i download the templates (following your instructions from the youtube video).

Good morning, sorry for the inconvenience, could you tell me how to do this?

**Comment by leandro8687** [comment]
> You need to change the local path to current directory of **wp3**, go to the directory when you make download and execute the command again.

Good morning, sorry for the inconvenience, could you tell me how to do this?

**Comment by mh4x0f** [comment]
@leandro8687 i fixed this bug now for captive flask extra repository this a error  https://github.com/mh4x0f/extra-captiveflask/commit/848a6fef544d30a1b6514ef1b761d73de9a7cc83

![image](https://github.com/P0cL4bs/wifipumpkin3/assets/6795613/0bf23fbf-2c62-4451-b765-ec2713292e4a)
