### ISSUE TITLE
Starting access point with captiveflask plugins. (I have already read the closed issue)

### ISSUE THREAD

**Issue by stelladim** [P0cL4bs/wifipumpkin3#77]
Hello again!

I’m having one more problem with captiveflask. I followed the instructions of your youtube video [Facebook captive login templates with wifipumpkin3](https://www.youtube.com/watch?v=0TPWLZ8_-mM&feature=youtu.be) and when I set captiveflask plugin to any option besides DarkLogin, I’m getting the following error when I start the access point.

wp3 > start
[+] enable forwarding in iptables...
[] sharing internet connection with NAT...
[] settings for captive portal:
[] allow FORWARD UDP DNS
[] allow traffic to captive portal
[] block all other traffic in access point
[] redirecting HTTP traffic to captive portal
Traceback (most recent call last):
File "/usr/local/bin/wifipumpkin3", line 11, in
load_entry_point('wifipumpkin3==1.0.7', 'console_scripts', 'wifipumpkin3')()
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/main.py", line 106, in main
prompt.cmdloop("Starting prompt...")
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 44, in cmdloop
super(ConsoleUI, self).cmdloop(intro="")
File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
stop = self.onecmd(line)
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 166, in onecmd
Cmd.onecmd(self, command)
File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
return func(arg)
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/console.py", line 185, in do_use
return module.cmdloop()
File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
stop = self.onecmd(line)
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 342, in onecmd
Cmd.onecmd(self, command)
File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
return func(arg)
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 264, in do_back
self.root["PumpkinShell"].getInstance().cmdloop("Starting prompt...")
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 44, in cmdloop
super(ConsoleUI, self).cmdloop(intro="")
File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
stop = self.onecmd(line)
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/terminal.py", line 166, in onecmd
Cmd.onecmd(self, command)
File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
return func(arg)
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/console.py", line 216, in do_start
ctr_instance.Start()
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/controllers/proxycontroller.py", line 128, in Start
self.Active.boot()
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/servers/proxy/captiveflask.py", line 124, in boot
self.reactor = ProcessThread({"captiveflask": self.CMD_ARRAY})
AttributeError: 'CaptivePortal' object has no attribute 'CMD_ARRAY'
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
QProcess: Destroyed while process ("iptables") is still running.
Exception ignored in: <function WorkerProcess.del at 0x7fe601c83d30>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/threads.py", line 237, in del
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.del at 0x7fe601c83d30>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/threads.py", line 237, in del
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.del at 0x7fe601c83d30>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/threads.py", line 237, in del
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.del at 0x7fe601c83d30>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/threads.py", line 237, in del
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.del at 0x7fe601c83d30>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/threads.py", line 237, in del
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Exception ignored in: <function WorkerProcess.del at 0x7fe601c83d30>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3/core/common/threads.py", line 237, in del
RuntimeError: wrapped C/C++ object of type QProcess has been deleted

I have already read the issue #72 , but I couldn't understand what I should change on the configuration file. I have the default settings as they are show in the [documentation](https://wifipumpkin3.github.io/docs/configuration/configuration-file#dhcp-server-configuration).  

Desktop (please complete the following information):
Wifipumpkin3 version: 1.0.7.
Virtual Machine (yes or no and which): yes, VMware Workstation 15.5 Pro
Operating System: Kali Linux
Version: 2020.3

Thanks in advance!

**Comment by mh4x0f** [comment]
it not the same problem with #72. maybe the problem will be solve only execute the more one command:
``` sh 
sudo python3 setup.py install
```
OBS: this commad above you can to execute on the root folder on wifipumpkin3 local machine.

**Comment by exactsameproblem** [comment]
Hello, I did a fresh (re)install on Kali 2021:

sudo wifipumkin3
set interface <iface>
set ssid <ssid>
set proxy captiveflask
start

and I get this error.
