### ISSUE TITLE
hey guys I have some terrible problem

### ISSUE THREAD

**Issue by Webster1234** [P0cL4bs/wifipumpkin3#98]
**Description of the bug or feature request**

**To Reproduce**

1. After I install the wifipumpkin I run the command "wifipumpkin3", "wifipumpkin3 -i wlan0mon"

2.And it return back to me like that

root@kali:~# wifipumpkin3 -i wlan0mon

                             Jgy__
                            jWW  `""9Wf
                          _#WWW     IW
                         jWWWWW     IW
                 __,yyyyyWWWWW     IWyyyy___
            _jyWWP"^``"`.C"9*,J _.mqD:^^"WWWWWWQg__
          jgW"^.C/"    .C'     I    `D.     'D._"WQg_
        jWP` .C"       C'      I     `D._     `D._ "Qg_
      jQP`  .C    ,d^^b._      I      _.d^^b.   `D._ "Qg
     jQ^  .C"   /`   .+" \     I     / "+.   `\   `D.  XQ
    jQ'  .C'   |`  ."    )    _I    (     ".  |    `D.  4#
    Qf  .C     (   (    /    / /\    \     )  )     `D.  Qg
   jW   C'      \__\_.+'    / /  \    `+._/__/       `D  jQ
   Qf   C         C        /_/    \         D         D   Qk
   Qf   C      _  C        \_\____/         D  _      D   QF
   QL   C      \`+.__     _______     ______.+'/      D   QF
   B&   C.      \   \|    ||     |    ||      /       D   Qf
   jQ   `C.      \   |____|/     |____|/__   /      .D'   jW
    TQ   `C.      \._   `+.__________/___/|_/      .D'   jQ`
     9Q   `C.      C.`+._           |   |/.D'     .D'   jQ'
      "Qg  `C.     `C.   `"+-------'   ' .D'     .D'   pW`
       ^WQy `C.     `C.        I        .D'    _.D' yW"
         ^9Qy_`C.    `C.       I       .D'   _.D jgW"
            `9WQgC.__ `C.      I      .D'  _.Dp@@"`
           ilmk `""9WQQggyyyyyygyyyyyQggQWQH""
                                            codename: AKUANDUBA
by: @mh4x0f - P0cL4bs Team | version: 1.0.7 
[*] Session id: f70def0c-0c6a-11eb-b7c9-000c29d6bdc5 
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.0.7', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/__main__.py", line 105, in main
    prompt = PumpkinShell(parse_args)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/console.py", line 62, in __init__
    super(PumpkinShell, self).__init__(parse_args=self.parse_args)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 36, in __init__
    self.initialize_core()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/console.py", line 77, in initialize_core
    self.coreui = DefaultController(self)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/controllers/defaultcontroller.py", line 46, in __init__
    __defaultui = [ui(parent, self.FSettings) for ui in TabsWidget.__subclasses__()]
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/controllers/defaultcontroller.py", line 46, in <listcomp>
    __defaultui = [ui(parent, self.FSettings) for ui in TabsWidget.__subclasses__()]
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/widgets/default/session_config.py", line 38, in __init__
    settingsItem = [
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/widgets/default/session_config.py", line 39, in <listcomp>
    setitem(self.parent) for setitem in CoreSettings.__subclasses__()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/wirelessmode/static.py", line 148, in __init__
    self.interfaces = Linux.get_interfaces()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/platforms.py", line 72, in get_interfaces
    interfaces["all"] = netifaces.interfaces()
AttributeError: module 'netifaces' has no attribute 'interfaces'
***************************************************************

**Desktop (please complete the following information):**

* Wifipumpkin3 version : wifipumkin3 v1.0.7

* Virtual Machine (yes or no and which):   yes

* Operating System: kali linux

* version:  2020.3

**Comment by giuliaContardi** [comment]
I have the same problem right after installing wifipumpkin3!
```

`root@kali:~# sudo  wifipumpkin3

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$PR$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$$"    @$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$"      '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$                 """"""#*R$$$$$$$$$$$$$
$$$$$$$$$$$$$P"..::!~ .....    .<!!!!!!!:  ~!!!:.. "*$$$$$$$$$
$$$$$$$$$$".<!!!!~  <!!!!!!!~ !!!!!!!!!!!!!  !!!!!!!: "$$$$$$$
$$$$$$$P <!!!!!~ .!!!!!!!!!! !!!!!!!!!!!!!!!. `!!!!!!!: "$$$$$
$$$$$P :!!!!!~ .!!!!~!!!!!! .!!!!!!!!!~!!!!!!: '!!!!!!!! '$$$$
$$$$# !!!!!f  !!!`   `!!!!! :!!!!!!!!!    `!!!! `!!!!!!!! '$$$
$$$F !!!!!!  !!~      '!!!f  4!!!!!!!!       !!> 4!!!!!!!> 9$$
$$P <!!!!!  !!>        '!!~   '!!!!!!........<!!  !!!!!!!! <$$
$$> !!!!!! ~!!!!!!!!!!!!!~      `!!!!!!!!!!!!!!!> `!!!!!!!  $$
$$ '!!!!!! '!!!!!!!!!!!!!!> !!!!!!!!!!!!!!(``~!!!  !!!!!!f 4$$
$$r!!!!!!! `!!~   :<!!!!!!! `!!!!!!!!!!!!!~    `! '!!!!!!> .$$
$$L !!!!!!. !!:h   `!!!!!!! `!!!!!!!!!~     <!!!!  !!!!!!  @$$
$$$ `!!!!!! ~!!!!       `~~ '~~~~~`        !!!!!f .!!!!!  <$$$
$$$N ~!!!!!! !!!!!h.           ..::     .!!!!!!!  :!!!!` .$$$$
$$$$$. ~!!!!> !!!!!!!!:       `!!!!!h!!!!!!!!!!~  !!!!  d$$$$$
$$$$$$N. `!!!. !!!!!!!!!!!!! ~!!!!!!!!!!!!!!!!~  !!~ .e$$$$$$$
$$$$$$$$$bu  `  '!!!!!!!!!!~  !!!!!!!!!!!!!~` .uuue$$$$$$$$$$$
$$$$$$$$$$$$$$$$e.  ````   wifi     ```   .e$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
                                            codename: AKUANDUBA
by: @mh4x0f - P0cL4bs Team | version: 1.0.7 
[*] Session id: c059c9c8-0fb6-11eb-84d9-f48c50a26656 
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.0.7', 'console_scripts', 'wifipumpkin3')())
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/__main__.py", line 105, in main
    prompt = PumpkinShell(parse_args)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/console.py", line 62, in __init__
    super(PumpkinShell, self).__init__(parse_args=self.parse_args)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 36, in __init__
    self.initialize_core()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/console.py", line 77, in initialize_core
    self.coreui = DefaultController(self)
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/controllers/defaultcontroller.py", line 46, in __init__
    __defaultui = [ui(parent, self.FSettings) for ui in TabsWidget.__subclasses__()]
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/controllers/defaultcontroller.py", line 46, in <listcomp>
    __defaultui = [ui(parent, self.FSettings) for ui in TabsWidget.__subclasses__()]
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/widgets/default/session_config.py", line 38, in __init__
    settingsItem = [
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/widgets/default/session_config.py", line 39, in <listcomp>
    setitem(self.parent) for setitem in CoreSettings.__subclasses__()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/wirelessmode/docker.py", line 200, in __init__
    self.interfaces = Linux.get_interfaces()
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/platforms.py", line 72, in get_interfaces
    interfaces["all"] = netifaces.interfaces()
```

`AttributeError: module 'netifaces' has no attribute 'interfaces'`

The difference is that I install Kali linux 2020.3 dual-boot and not in a VM.

**Comment by mh4x0f** [comment]
@Webster1234 @giuliaContardi run this command above and send me the output:
``` sh
pip3 freeze | grep netifaces
```

**Comment by giuliaContardi** [comment]
> @Webster1234 @giuliaContardi run this command above and send me the output:
> 
> ```shell
> pip3 freeze | grep netifaces
> ```

Thank you so much for helping me!

Here it is:
```
root@kali:~# pip3 freeze | grep netifaces
netifaces==0.10.9
```

**Comment by mh4x0f** [comment]
try to reinstall the module netifaces:
``` sh
sudo pip3 uninstall netifaces==0.10.9
sudo pip3 install netifaces==0.10.9
```
and try run again, if you got same error try with another distribution. Kali linux  is unstable, I don't recommend

**Comment by Webster1234** [comment]
sorry I am late

this is the command:

netifaces==0.10.9

**Comment by Webster1234** [comment]
Oh my god it works for me !

thx a lot
